version: '3'
services:

    db:
        image: mysql:5.7.22
        restart: always
        ports:
          - "3390:3306"
        environment:
          - MYSQL_DATABASE=weather-db
          - MYSQL_USER=root
          - MYSQL_ROOT_PASSWORD=1234
          - MYSQL_PASSWORD=1234
        volumes:
          - "./container/data/db/mysql:/var/lib/mysql"

    api:
        build: ./
        restart: always
        tty: true
        ports:
          - "8000:80"
        volumes:
          - "./container/logs/nginx:/var/log/nginx"
          - "./:/var/www/"
        depends_on:
          - db
        links:
          - db
